name             'openbay'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures openbay'
long_description 'Installs/Configures openbay'
version          '0.1.0'

depends 'application'
depends 'application_php'
depends 'apache2'
depends 'php'
